disable_existing_loggers: false
formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
  file:
    backupCount: 30
    class: logging.handlers.TimedRotatingFileHandler
    filename: ./log/XiaoYueLog.log
    interval: 1
    when: midnight
loggers:
  ? ''
  : handlers:
    - console
    - file
    level: DEBUG
    propagate: false
version: 1
